kraken:
  repository: gcr.io/uber-container-tools
  tag: v0.1.1
  imagePullPolicy: IfNotPresent
  tracker_port: 30011
  build_index_port: 30021
  origin_port: 30031
  proxy_port: 30041
  registry_port: 30051

tracker:
  config: /etc/config/tracker.yaml
  replicas: 3
  hostNetwork: true
  tolerations:
    - key: "node.kubernetes.io/not-ready"
      operator: "Exists"
      effect: "NoSchedule"
  affinity:
    - labelSelector:
        matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
              - kraken
      topologyKey: kubernetes.io/hostname
  extraVolumes:
#  - name: nginx-cache
#    hostPath:
#      path: /data/nginx
  extraVolumeMounts:
#  - name: nginx-cache
#    mountPath: /var/cache/kraken/kraken-origin/nginx/
#  annotations: |
#    foo.example.com/release: "{{ .Release.Name }}"
#  initContainers:
#    - name: foo
#      image: alpine:latest
#      command: ["sh", "-c", "echo hello"]
#      volumeMounts:
#        - name: config
#          mountPath: /etc/config

build_index:
  config: /etc/config/build-index.yaml
  replicas: 3
  annotations:
  extraVolumes:
  extraVolumeMounts:
  initContainers:
  hostNetwork: true
  tolerations:
    - key: "node.kubernetes.io/not-ready"
      operator: "Exists"
      effect: "NoSchedule"
  affinity:
    - labelSelector:
        matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
              - kraken
      topologyKey: kubernetes.io/hostname
#  extraBackends: |-
#    - namespace: library/.*
#      backend:
#        registry_tag:
#          address: my.private.registry
#          security:
#            basic:
#              username: "joebloggs"
#              password: "12345"

origin:
  config: /etc/config/origin.yaml
  replicas: 3
  annotations:
  extraVolumes:
  extraVolumeMounts:
  initContainers:
  hostNetwork: true
  tolerations:
    - key: "node.kubernetes.io/not-ready"
      operator: "Exists"
      effect: "NoSchedule"
  affinity:
    - labelSelector:
        matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
              - kraken
      topologyKey: kubernetes.io/hostname
  imagePullSecrets:
    - name: nvcr.io
  image: "nvcr.io/nv-ngn/sdn-dev/akorobkov:kraken-origin"
#  extraBackends: |-
#    - namespace: library/.*
#      backend:
#        registry_blob:
#          address: my.private.registry
#          security:
#            basic:
#              username: "joebloggs"
#              password: "12345"

proxy:
  config: /etc/config/proxy.yaml
  replicas: 1
  annotations:
  extraVolumes:
  extraVolumeMounts:
  initContainers:
  hostNetwork: true
  tolerations:
    - key: "node.kubernetes.io/not-ready"
      operator: "Exists"
      effect: "NoSchedule"
  affinity:
    - labelSelector:
        matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
              - kraken
      topologyKey: kubernetes.io/hostname

agent:
  config: /etc/config/agent.yaml
  annotations:
  extraVolumes:
  extraVolumeMounts:
  initContainers:
  hostNetwork: true
  tolerations:
    - operator: "Exists"
  affinity:
    - labelSelector:
        matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
              - kraken
      topologyKey: kubernetes.io/hostname
  nodeSelector:
    agents-group: kraken-agent
  imagePullSecrets:
    - name: nvcr.io
  image: "nvcr.io/nv-ngn/sdn-dev/akorobkov:kraken-agent"
testfs:
  enabled: true
  hostNetwork: true
  tolerations:
    - key: "node.kubernetes.io/not-ready"
      operator: "Exists"
      effect: "NoSchedule"
  annotations:
